version: '3.7'

services:
  paper:
    build: .
    container_name: debug_kotlin
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
      - 5005:5005
    volumes:
      - ./.docker:/data
    entrypoint:
      - /docker-setup-plugin